project_id = "krphkpliaoitytorrpcv"

[functions.stripe-webhook]
verify_jwt = false

[functions.check-notifications]
verify_jwt = false

[functions.generate-leads]
verify_jwt = false

[functions.send-campaign]
verify_jwt = false
